# Generated by Django 6.1.1 on 2026-09-16 07:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=250)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category')),
                ('destination_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='wallets.wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['user', 'transaction_date'], name='transaction_user_id_e55ebe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('destination_wallet__isnull', False), ('transaction_type', 'TRANSFER')), models.Q(('category__isnull', False), ('destination_wallet__isnull', True), ('transaction_type__in', ['INCOME', 'EXPENSE'])), _connector='OR'), name='transaction_valid_relationships'), models.CheckConstraint(condition=models.Q(('destination_wallet__isnull', True), models.Q(('wallet', models.F('destination_wallet')), _negated=True), _connector='OR'), name='transaction_different_wallets')],
            },
        ),
    ]
