# Generated by Django 6.1.1 on 2026-09-16 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BUDGET', 'Budget'), ('SAVINGS', 'Savings'), ('REPORT', 'Report')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('target_id', models.PositiveBigIntegerField()),
                ('event_key', models.CharField(max_length=150)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='notification_unique_recipient_event')],
            },
        ),
    ]
